// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ANAFError struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
}

type Address struct {
	ID             string    `json:"id"`
	UserID         string    `json:"userId"`
	Label          string    `json:"label"`
	StreetAddress  string    `json:"streetAddress"`
	Apartment      *string   `json:"apartment,omitempty"`
	City           string    `json:"city"`
	County         string    `json:"county"`
	PostalCode     *string   `json:"postalCode,omitempty"`
	Country        string    `json:"country"`
	AdditionalInfo *string   `json:"additionalInfo,omitempty"`
	IsDefault      bool      `json:"isDefault"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type AdminEditBookingInput struct {
	ScheduledDate       *time.Time   `json:"scheduledDate,omitempty"`
	ScheduledTime       *time.Time   `json:"scheduledTime,omitempty"`
	ServiceType         *ServiceType `json:"serviceType,omitempty"`
	EstimatedHours      *int         `json:"estimatedHours,omitempty"`
	AreaSqm             *int         `json:"areaSqm,omitempty"`
	SpecialInstructions *string      `json:"specialInstructions,omitempty"`
	AccessInstructions  *string      `json:"accessInstructions,omitempty"`
}

type AdminKPIs struct {
	Period              KPIPeriod         `json:"period"`
	TotalRevenue        float64           `json:"totalRevenue"`
	PlatformFees        float64           `json:"platformFees"`
	TotalBookings       int               `json:"totalBookings"`
	CompletedBookings   int               `json:"completedBookings"`
	ActiveBookings      int               `json:"activeBookings"`
	CancelledBookings   int               `json:"cancelledBookings"`
	ActiveCleaners      int               `json:"activeCleaners"`
	ActiveClients       int               `json:"activeClients"`
	AverageBookingValue float64           `json:"averageBookingValue"`
	TopCleaners         []*TopCleanerStat `json:"topCleaners"`
}

type Availability struct {
	ID           string           `json:"id"`
	CleanerID    string           `json:"cleanerId"`
	Type         AvailabilityType `json:"type"`
	DayOfWeek    *int             `json:"dayOfWeek,omitempty"`
	SpecificDate *time.Time       `json:"specificDate,omitempty"`
	StartTime    string           `json:"startTime"`
	EndTime      string           `json:"endTime"`
	IsActive     bool             `json:"isActive"`
	Notes        *string          `json:"notes,omitempty"`
	CreatedAt    time.Time        `json:"createdAt"`
	UpdatedAt    time.Time        `json:"updatedAt"`
}

type AvailabilityData struct {
	HoursPerWeek             string   `json:"hoursPerWeek"`
	Areas                    []string `json:"areas"`
	Days                     []string `json:"days"`
	TimeSlots                []string `json:"timeSlots"`
	EstimatedMonthlyEarnings *float64 `json:"estimatedMonthlyEarnings,omitempty"`
}

type AvailabilityInput struct {
	HoursPerWeek string   `json:"hoursPerWeek"`
	Areas        []string `json:"areas"`
	Days         []string `json:"days"`
	TimeSlots    []string `json:"timeSlots"`
}

type Booking struct {
	ID                     string        `json:"id"`
	ReservationCode        *string       `json:"reservationCode,omitempty"`
	ClientID               string        `json:"clientId"`
	Client                 *User         `json:"client,omitempty"`
	CleanerID              *string       `json:"cleanerId,omitempty"`
	Cleaner                *User         `json:"cleaner,omitempty"`
	AddressID              string        `json:"addressId"`
	Address                *Address      `json:"address,omitempty"`
	ServiceType            ServiceType   `json:"serviceType"`
	AreaSqm                *int          `json:"areaSqm,omitempty"`
	EstimatedHours         int           `json:"estimatedHours"`
	Frequency              *string       `json:"frequency,omitempty"`
	ScheduledDate          *time.Time    `json:"scheduledDate,omitempty"`
	ScheduledTime          *time.Time    `json:"scheduledTime,omitempty"`
	TimePreferences        *string       `json:"timePreferences,omitempty"`
	IncludesDeepCleaning   bool          `json:"includesDeepCleaning"`
	IncludesWindows        bool          `json:"includesWindows"`
	IncludesCarpetCleaning bool          `json:"includesCarpetCleaning"`
	IncludesFridge         bool          `json:"includesFridge"`
	IncludesOven           bool          `json:"includesOven"`
	IncludesBalcony        bool          `json:"includesBalcony"`
	NumberOfWindows        int           `json:"numberOfWindows"`
	CarpetAreaSqm          int           `json:"carpetAreaSqm"`
	BasePrice              float64       `json:"basePrice"`
	AddonsPrice            float64       `json:"addonsPrice"`
	TotalPrice             float64       `json:"totalPrice"`
	PlatformFee            float64       `json:"platformFee"`
	CleanerPayout          float64       `json:"cleanerPayout"`
	DiscountApplied        float64       `json:"discountApplied"`
	Status                 BookingStatus `json:"status"`
	SpecialInstructions    *string       `json:"specialInstructions,omitempty"`
	AccessInstructions     *string       `json:"accessInstructions,omitempty"`
	ConfirmedAt            *time.Time    `json:"confirmedAt,omitempty"`
	StartedAt              *time.Time    `json:"startedAt,omitempty"`
	CompletedAt            *time.Time    `json:"completedAt,omitempty"`
	CancelledAt            *time.Time    `json:"cancelledAt,omitempty"`
	CancelledBy            *string       `json:"cancelledBy,omitempty"`
	CancellationReason     *string       `json:"cancellationReason,omitempty"`
	ClientRating           *int          `json:"clientRating,omitempty"`
	ClientReview           *string       `json:"clientReview,omitempty"`
	CleanerRating          *int          `json:"cleanerRating,omitempty"`
	CleanerReview          *string       `json:"cleanerReview,omitempty"`
	CreatedAt              time.Time     `json:"createdAt"`
	UpdatedAt              time.Time     `json:"updatedAt"`
}

type Checkin struct {
	ID                string     `json:"id"`
	BookingID         string     `json:"bookingId"`
	CleanerID         string     `json:"cleanerId"`
	CheckInTime       *time.Time `json:"checkInTime,omitempty"`
	CheckInLatitude   *float64   `json:"checkInLatitude,omitempty"`
	CheckInLongitude  *float64   `json:"checkInLongitude,omitempty"`
	CheckOutTime      *time.Time `json:"checkOutTime,omitempty"`
	CheckOutLatitude  *float64   `json:"checkOutLatitude,omitempty"`
	CheckOutLongitude *float64   `json:"checkOutLongitude,omitempty"`
	TotalHoursWorked  *float64   `json:"totalHoursWorked,omitempty"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
}

type Cleaner struct {
	ID                      string         `json:"id"`
	UserID                  string         `json:"userId"`
	PhoneNumber             string         `json:"phoneNumber"`
	DateOfBirth             *string        `json:"dateOfBirth,omitempty"`
	StreetAddress           *string        `json:"streetAddress,omitempty"`
	City                    *string        `json:"city,omitempty"`
	County                  *string        `json:"county,omitempty"`
	PostalCode              *string        `json:"postalCode,omitempty"`
	YearsOfExperience       int            `json:"yearsOfExperience"`
	Bio                     *string        `json:"bio,omitempty"`
	Specializations         []string       `json:"specializations"`
	Languages               []string       `json:"languages"`
	Iban                    *string        `json:"iban,omitempty"`
	IDDocumentURL           *string        `json:"idDocumentURL,omitempty"`
	IDDocumentVerified      bool           `json:"idDocumentVerified"`
	BackgroundCheckURL      *string        `json:"backgroundCheckURL,omitempty"`
	BackgroundCheckVerified bool           `json:"backgroundCheckVerified"`
	ProfilePhotoURL         *string        `json:"profilePhotoURL,omitempty"`
	AverageRating           *float64       `json:"averageRating,omitempty"`
	TotalJobs               int            `json:"totalJobs"`
	TotalEarnings           float64        `json:"totalEarnings"`
	ApprovalStatus          ApprovalStatus `json:"approvalStatus"`
	IsActive                bool           `json:"isActive"`
	IsAvailable             bool           `json:"isAvailable"`
	CreatedAt               time.Time      `json:"createdAt"`
	UpdatedAt               time.Time      `json:"updatedAt"`
}

type CleanerApplication struct {
	ID                   string                  `json:"id"`
	SessionID            *string                 `json:"sessionId,omitempty"`
	UserID               *string                 `json:"userId,omitempty"`
	CurrentStep          int                     `json:"currentStep"`
	Status               ApplicationStatus       `json:"status"`
	ApplicationData      *CleanerApplicationData `json:"applicationData"`
	ReviewedBy           *User                   `json:"reviewedBy,omitempty"`
	ReviewedAt           *time.Time              `json:"reviewedAt,omitempty"`
	RejectionReason      *string                 `json:"rejectionReason,omitempty"`
	AdminNotes           *string                 `json:"adminNotes,omitempty"`
	ConvertedToCleanerID *string                 `json:"convertedToCleanerId,omitempty"`
	CreatedAt            time.Time               `json:"createdAt"`
	UpdatedAt            time.Time               `json:"updatedAt"`
	SubmittedAt          *time.Time              `json:"submittedAt,omitempty"`
}

type CleanerApplicationData struct {
	Eligibility  *EligibilityData  `json:"eligibility,omitempty"`
	Availability *AvailabilityData `json:"availability,omitempty"`
	Profile      *ProfileData      `json:"profile,omitempty"`
	Legal        *LegalData        `json:"legal,omitempty"`
	Documents    *DocumentData     `json:"documents,omitempty"`
}

type CleanerApplicationInput struct {
	SessionID    *string            `json:"sessionId,omitempty"`
	UserID       *string            `json:"userId,omitempty"`
	CurrentStep  int                `json:"currentStep"`
	Eligibility  *EligibilityInput  `json:"eligibility,omitempty"`
	Availability *AvailabilityInput `json:"availability,omitempty"`
	Profile      *ProfileInput      `json:"profile,omitempty"`
	Legal        *LegalInput        `json:"legal,omitempty"`
	Documents    *DocumentInput     `json:"documents,omitempty"`
}

type Client struct {
	ID                string    `json:"id"`
	UserID            string    `json:"userId"`
	PhoneNumber       *string   `json:"phoneNumber,omitempty"`
	PreferredLanguage string    `json:"preferredLanguage"`
	TotalBookings     int       `json:"totalBookings"`
	TotalSpent        float64   `json:"totalSpent"`
	AverageRating     *float64  `json:"averageRating,omitempty"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type Company struct {
	ID                 string                `json:"id"`
	Name               string                `json:"name"`
	Cui                string                `json:"cui"`
	RegistrationNumber *string               `json:"registrationNumber,omitempty"`
	Iban               *string               `json:"iban,omitempty"`
	BankName           *string               `json:"bankName,omitempty"`
	LegalAddress       *string               `json:"legalAddress,omitempty"`
	ContactEmail       *string               `json:"contactEmail,omitempty"`
	ContactPhone       *string               `json:"contactPhone,omitempty"`
	ApprovalStatus     CompanyApprovalStatus `json:"approvalStatus"`
	RejectedReason     *string               `json:"rejectedReason,omitempty"`
	IsActive           bool                  `json:"isActive"`
	CreatedAt          time.Time             `json:"createdAt"`
	UpdatedAt          time.Time             `json:"updatedAt"`
}

type CompanyCleaner struct {
	ID        string     `json:"id"`
	CompanyID string     `json:"companyId"`
	CleanerID string     `json:"cleanerId"`
	Cleaner   *Cleaner   `json:"cleaner"`
	Status    string     `json:"status"`
	JoinedAt  time.Time  `json:"joinedAt"`
	LeftAt    *time.Time `json:"leftAt,omitempty"`
}

type CompanyStats struct {
	TotalTeamMembers  int      `json:"totalTeamMembers"`
	ActiveTeamMembers int      `json:"activeTeamMembers"`
	TotalBookings     int      `json:"totalBookings"`
	ActiveBookings    int      `json:"activeBookings"`
	CompletedBookings int      `json:"completedBookings"`
	TotalRevenue      float64  `json:"totalRevenue"`
	MonthlyRevenue    float64  `json:"monthlyRevenue"`
	AverageRating     *float64 `json:"averageRating,omitempty"`
}

type CreateAddressInput struct {
	Label          string  `json:"label"`
	StreetAddress  string  `json:"streetAddress"`
	Apartment      *string `json:"apartment,omitempty"`
	City           string  `json:"city"`
	County         string  `json:"county"`
	PostalCode     *string `json:"postalCode,omitempty"`
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	IsDefault      *bool   `json:"isDefault,omitempty"`
}

type CreateAvailabilityInput struct {
	Type         AvailabilityType `json:"type"`
	DayOfWeek    *int             `json:"dayOfWeek,omitempty"`
	SpecificDate *time.Time       `json:"specificDate,omitempty"`
	StartTime    string           `json:"startTime"`
	EndTime      string           `json:"endTime"`
	IsActive     *bool            `json:"isActive,omitempty"`
	Notes        *string          `json:"notes,omitempty"`
}

type CreateBookingInput struct {
	AddressID            string      `json:"addressId"`
	ServiceType          ServiceType `json:"serviceType"`
	AreaSqm              *int        `json:"areaSqm,omitempty"`
	EstimatedHours       int         `json:"estimatedHours"`
	ScheduledDate        *time.Time  `json:"scheduledDate,omitempty"`
	ScheduledTime        *time.Time  `json:"scheduledTime,omitempty"`
	TimePreferences      *string     `json:"timePreferences,omitempty"`
	IncludesDeepCleaning bool        `json:"includesDeepCleaning"`
	IncludesWindows      bool        `json:"includesWindows"`
	NumberOfWindows      int         `json:"numberOfWindows"`
	IncludesCarpet       bool        `json:"includesCarpet"`
	CarpetAreaSqm        int         `json:"carpetAreaSqm"`
	IncludesFridge       *bool       `json:"includesFridge,omitempty"`
	IncludesOven         *bool       `json:"includesOven,omitempty"`
	IncludesBalcony      *bool       `json:"includesBalcony,omitempty"`
	SpecialInstructions  *string     `json:"specialInstructions,omitempty"`
	AccessInstructions   *string     `json:"accessInstructions,omitempty"`
	Supplies             string      `json:"supplies"`
	Frequency            *string     `json:"frequency,omitempty"`
}

type CreateCleanerProfileInput struct {
	PhoneNumber       string   `json:"phoneNumber"`
	DateOfBirth       *string  `json:"dateOfBirth,omitempty"`
	StreetAddress     *string  `json:"streetAddress,omitempty"`
	City              *string  `json:"city,omitempty"`
	County            *string  `json:"county,omitempty"`
	PostalCode        *string  `json:"postalCode,omitempty"`
	YearsOfExperience int      `json:"yearsOfExperience"`
	Bio               *string  `json:"bio,omitempty"`
	Specializations   []string `json:"specializations,omitempty"`
	Languages         []string `json:"languages,omitempty"`
}

type CreateCompanyInput struct {
	Name               string  `json:"name"`
	Cui                string  `json:"cui"`
	RegistrationNumber *string `json:"registrationNumber,omitempty"`
	Iban               *string `json:"iban,omitempty"`
	BankName           *string `json:"bankName,omitempty"`
	LegalAddress       *string `json:"legalAddress,omitempty"`
	ContactEmail       *string `json:"contactEmail,omitempty"`
	ContactPhone       *string `json:"contactPhone,omitempty"`
}

type CreateDisputeInput struct {
	BookingID   string      `json:"bookingId"`
	DisputeType DisputeType `json:"disputeType"`
	Description string      `json:"description"`
}

type CreateReviewInput struct {
	BookingID string  `json:"bookingId"`
	Rating    int     `json:"rating"`
	Comment   *string `json:"comment,omitempty"`
}

type Dispute struct {
	ID                 string                 `json:"id"`
	BookingID          string                 `json:"bookingId"`
	CreatedBy          string                 `json:"createdBy"`
	AssignedTo         *string                `json:"assignedTo,omitempty"`
	DisputeType        DisputeType            `json:"disputeType"`
	Status             DisputeStatus          `json:"status"`
	Description        string                 `json:"description"`
	ResolutionType     *DisputeResolutionType `json:"resolutionType,omitempty"`
	ResolutionNotes    *string                `json:"resolutionNotes,omitempty"`
	RefundAmount       *float64               `json:"refundAmount,omitempty"`
	ResolvedAt         *time.Time             `json:"resolvedAt,omitempty"`
	ResolvedBy         *string                `json:"resolvedBy,omitempty"`
	CleanerResponse    *string                `json:"cleanerResponse,omitempty"`
	CleanerRespondedAt *time.Time             `json:"cleanerRespondedAt,omitempty"`
	CreatedAt          time.Time              `json:"createdAt"`
	UpdatedAt          time.Time              `json:"updatedAt"`
}

type DocumentData struct {
	CazierURL    *string `json:"cazierUrl,omitempty"`
	IDFrontURL   *string `json:"idFrontUrl,omitempty"`
	IDBackURL    *string `json:"idBackUrl,omitempty"`
	InsuranceURL *string `json:"insuranceUrl,omitempty"`
}

type DocumentInput struct {
	CazierURL    *string `json:"cazierUrl,omitempty"`
	IDFrontURL   *string `json:"idFrontUrl,omitempty"`
	IDBackURL    *string `json:"idBackUrl,omitempty"`
	InsuranceURL *string `json:"insuranceUrl,omitempty"`
}

type EarningPotential struct {
	WeeklyMin         float64 `json:"weeklyMin"`
	WeeklyMax         float64 `json:"weeklyMax"`
	MonthlyMin        float64 `json:"monthlyMin"`
	MonthlyMax        float64 `json:"monthlyMax"`
	BaseRate          float64 `json:"baseRate"`
	TopCleanerMonthly float64 `json:"topCleanerMonthly"`
}

type EligibilityData struct {
	Age18Plus  bool   `json:"age18Plus"`
	WorkRight  string `json:"workRight"`
	Experience string `json:"experience"`
}

type EligibilityInput struct {
	Age18Plus  bool   `json:"age18Plus"`
	WorkRight  string `json:"workRight"`
	Experience string `json:"experience"`
}

type GeneratePayoutsInput struct {
	Year  int `json:"year"`
	Month int `json:"month"`
}

type Invoice struct {
	ID                  string        `json:"id"`
	BookingID           string        `json:"bookingId"`
	InvoiceNumber       string        `json:"invoiceNumber"`
	IssueDate           time.Time     `json:"issueDate"`
	DueDate             time.Time     `json:"dueDate"`
	ClientName          string        `json:"clientName"`
	ClientEmail         *string       `json:"clientEmail,omitempty"`
	CleanerName         string        `json:"cleanerName"`
	ServiceDescription  string        `json:"serviceDescription"`
	Subtotal            float64       `json:"subtotal"`
	TaxAmount           float64       `json:"taxAmount"`
	TotalAmount         float64       `json:"totalAmount"`
	Currency            string        `json:"currency"`
	Status              InvoiceStatus `json:"status"`
	PDFURL              *string       `json:"pdfUrl,omitempty"`
	XMLURL              *string       `json:"xmlUrl,omitempty"`
	CreatedAt           time.Time     `json:"createdAt"`
	UpdatedAt           time.Time     `json:"updatedAt"`
	AnafUploadIndex     *string       `json:"anafUploadIndex,omitempty"`
	AnafStatus          ANAFStatus    `json:"anafStatus"`
	AnafSubmittedAt     *time.Time    `json:"anafSubmittedAt,omitempty"`
	AnafProcessedAt     *time.Time    `json:"anafProcessedAt,omitempty"`
	AnafDownloadID      *string       `json:"anafDownloadId,omitempty"`
	AnafConfirmationURL *string       `json:"anafConfirmationUrl,omitempty"`
	AnafErrors          []*ANAFError  `json:"anafErrors,omitempty"`
	AnafRetryCount      int           `json:"anafRetryCount"`
	AnafLastRetryAt     *time.Time    `json:"anafLastRetryAt,omitempty"`
}

type LegalData struct {
	Status       string  `json:"status"`
	Cif          *string `json:"cif,omitempty"`
	CnpEncrypted string  `json:"cnpEncrypted"`
	Iban         string  `json:"iban"`
	BankName     *string `json:"bankName,omitempty"`
}

type LegalInput struct {
	Status       string  `json:"status"`
	Cif          *string `json:"cif,omitempty"`
	CnpEncrypted string  `json:"cnpEncrypted"`
	Iban         string  `json:"iban"`
	BankName     *string `json:"bankName,omitempty"`
}

type Message struct {
	ID         string    `json:"id"`
	BookingID  string    `json:"bookingId"`
	SenderID   string    `json:"senderId"`
	ReceiverID string    `json:"receiverId"`
	Content    string    `json:"content"`
	IsRead     bool      `json:"isRead"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	Sender     *User     `json:"sender,omitempty"`
	Receiver   *User     `json:"receiver,omitempty"`
	Booking    *Booking  `json:"booking,omitempty"`
}

type Mutation struct {
}

type Payment struct {
	ID                    string          `json:"id"`
	BookingID             string          `json:"bookingId"`
	UserID                string          `json:"userId"`
	Provider              PaymentProvider `json:"provider"`
	ProviderTransactionID *string         `json:"providerTransactionId,omitempty"`
	ProviderOrderID       *string         `json:"providerOrderId,omitempty"`
	PaymentType           PaymentType     `json:"paymentType"`
	Status                PaymentStatus   `json:"status"`
	Amount                float64         `json:"amount"`
	Currency              string          `json:"currency"`
	CardLastFour          *string         `json:"cardLastFour,omitempty"`
	CardBrand             *string         `json:"cardBrand,omitempty"`
	ErrorCode             *string         `json:"errorCode,omitempty"`
	ErrorMessage          *string         `json:"errorMessage,omitempty"`
	AuthorizedAt          *time.Time      `json:"authorizedAt,omitempty"`
	CapturedAt            *time.Time      `json:"capturedAt,omitempty"`
	FailedAt              *time.Time      `json:"failedAt,omitempty"`
	RefundedAt            *time.Time      `json:"refundedAt,omitempty"`
	CreatedAt             time.Time       `json:"createdAt"`
	UpdatedAt             time.Time       `json:"updatedAt"`
}

type Payout struct {
	ID                   string            `json:"id"`
	CleanerID            string            `json:"cleanerId"`
	PeriodStart          time.Time         `json:"periodStart"`
	PeriodEnd            time.Time         `json:"periodEnd"`
	Status               PayoutStatus      `json:"status"`
	TotalBookings        int               `json:"totalBookings"`
	TotalEarnings        float64           `json:"totalEarnings"`
	PlatformFees         float64           `json:"platformFees"`
	NetAmount            float64           `json:"netAmount"`
	Iban                 *string           `json:"iban,omitempty"`
	TransferReference    *string           `json:"transferReference,omitempty"`
	SettlementInvoiceURL *string           `json:"settlementInvoiceUrl,omitempty"`
	PaidAt               *time.Time        `json:"paidAt,omitempty"`
	FailedReason         *string           `json:"failedReason,omitempty"`
	CreatedAt            time.Time         `json:"createdAt"`
	UpdatedAt            time.Time         `json:"updatedAt"`
	LineItems            []*PayoutLineItem `json:"lineItems"`
}

type PayoutLineItem struct {
	ID              string    `json:"id"`
	PayoutID        string    `json:"payoutId"`
	BookingID       string    `json:"bookingId"`
	BookingDate     time.Time `json:"bookingDate"`
	ServiceType     string    `json:"serviceType"`
	BookingAmount   float64   `json:"bookingAmount"`
	PlatformFeeRate float64   `json:"platformFeeRate"`
	PlatformFee     float64   `json:"platformFee"`
	CleanerEarnings float64   `json:"cleanerEarnings"`
	CreatedAt       time.Time `json:"createdAt"`
}

type Photo struct {
	ID         string    `json:"id"`
	BookingID  *string   `json:"bookingId,omitempty"`
	DisputeID  *string   `json:"disputeId,omitempty"`
	UploadedBy string    `json:"uploadedBy"`
	PhotoType  PhotoType `json:"photoType"`
	FileName   string    `json:"fileName"`
	FileSize   int       `json:"fileSize"`
	MimeType   string    `json:"mimeType"`
	URL        string    `json:"url"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type PlatformSettings struct {
	ID                        string    `json:"id"`
	BasePrice                 float64   `json:"basePrice"`
	WeekendMultiplier         float64   `json:"weekendMultiplier"`
	EveningMultiplier         float64   `json:"eveningMultiplier"`
	PlatformFeePercent        float64   `json:"platformFeePercent"`
	EmailNotificationsEnabled bool      `json:"emailNotificationsEnabled"`
	AutoApprovalEnabled       bool      `json:"autoApprovalEnabled"`
	MaintenanceMode           bool      `json:"maintenanceMode"`
	UpdatedAt                 time.Time `json:"updatedAt"`
}

type PriceBreakdown struct {
	BasePricePerHour      float64 `json:"basePricePerHour"`
	HoursCharged          int     `json:"hoursCharged"`
	AreaPrice             float64 `json:"areaPrice"`
	WindowsPrice          float64 `json:"windowsPrice"`
	CarpetPrice           float64 `json:"carpetPrice"`
	TimeMultiplier        float64 `json:"timeMultiplier"`
	DiscountPercentage    float64 `json:"discountPercentage"`
	PlatformFeePercentage float64 `json:"platformFeePercentage"`
}

type PriceCalculationInput struct {
	CleaningType       string     `json:"cleaningType"`
	DurationHours      *float64   `json:"durationHours,omitempty"`
	AreaSize           *int       `json:"areaSize,omitempty"`
	ScheduledDate      *string    `json:"scheduledDate,omitempty"`
	ScheduledStartTime *time.Time `json:"scheduledStartTime,omitempty"`
	IncludesWindows    *bool      `json:"includesWindows,omitempty"`
	NumberOfWindows    *int       `json:"numberOfWindows,omitempty"`
	IncludesCarpet     *bool      `json:"includesCarpet,omitempty"`
	CarpetAreaSqm      *int       `json:"carpetAreaSqm,omitempty"`
	IncludesFridge     *bool      `json:"includesFridge,omitempty"`
	IncludesOven       *bool      `json:"includesOven,omitempty"`
	IncludesBalcony    *bool      `json:"includesBalcony,omitempty"`
	IncludesSupplies   *bool      `json:"includesSupplies,omitempty"`
	Frequency          *string    `json:"frequency,omitempty"`
}

type PriceQuote struct {
	BasePrice      float64         `json:"basePrice"`
	AddonsPrice    float64         `json:"addonsPrice"`
	Subtotal       float64         `json:"subtotal"`
	Discount       float64         `json:"discount"`
	PlatformFee    float64         `json:"platformFee"`
	TotalPrice     float64         `json:"totalPrice"`
	CleanerPayout  float64         `json:"cleanerPayout"`
	EstimatedHours int             `json:"estimatedHours"`
	Breakdown      *PriceBreakdown `json:"breakdown"`
}

type PriceQuoteInput struct {
	ServiceType     ServiceType `json:"serviceType"`
	AreaSqm         *int        `json:"areaSqm,omitempty"`
	EstimatedHours  int         `json:"estimatedHours"`
	ScheduledDate   time.Time   `json:"scheduledDate"`
	ScheduledTime   time.Time   `json:"scheduledTime"`
	IncludesWindows bool        `json:"includesWindows"`
	NumberOfWindows int         `json:"numberOfWindows"`
	IncludesCarpet  bool        `json:"includesCarpet"`
	CarpetAreaSqm   int         `json:"carpetAreaSqm"`
	Frequency       *string     `json:"frequency,omitempty"`
}

type ProfileData struct {
	PhotoURL  *string  `json:"photoUrl,omitempty"`
	Bio       string   `json:"bio"`
	Languages []string `json:"languages"`
	Equipment []string `json:"equipment"`
}

type ProfileInput struct {
	PhotoURL  *string  `json:"photoUrl,omitempty"`
	Bio       string   `json:"bio"`
	Languages []string `json:"languages"`
	Equipment []string `json:"equipment"`
}

type Query struct {
}

type ResolveDisputeInput struct {
	ResolutionType  DisputeResolutionType `json:"resolutionType"`
	ResolutionNotes string                `json:"resolutionNotes"`
	RefundAmount    *float64              `json:"refundAmount,omitempty"`
}

type Review struct {
	ID           string       `json:"id"`
	BookingID    string       `json:"bookingId"`
	ReviewerID   string       `json:"reviewerId"`
	RevieweeID   string       `json:"revieweeId"`
	ReviewerRole ReviewerRole `json:"reviewerRole"`
	Rating       int          `json:"rating"`
	Comment      *string      `json:"comment,omitempty"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    time.Time    `json:"updatedAt"`
}

type SendMessageInput struct {
	BookingID  string `json:"bookingId"`
	ReceiverID string `json:"receiverId"`
	Content    string `json:"content"`
}

type Session struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type TopCleanerStat struct {
	CleanerID     string   `json:"cleanerId"`
	CleanerName   string   `json:"cleanerName"`
	BookingCount  int      `json:"bookingCount"`
	TotalEarnings float64  `json:"totalEarnings"`
	AverageRating *float64 `json:"averageRating,omitempty"`
}

type UpdateAddressInput struct {
	Label          *string `json:"label,omitempty"`
	StreetAddress  *string `json:"streetAddress,omitempty"`
	Apartment      *string `json:"apartment,omitempty"`
	City           *string `json:"city,omitempty"`
	County         *string `json:"county,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	IsDefault      *bool   `json:"isDefault,omitempty"`
}

type UpdateAvailabilityInput struct {
	StartTime *string `json:"startTime,omitempty"`
	EndTime   *string `json:"endTime,omitempty"`
	IsActive  *bool   `json:"isActive,omitempty"`
	Notes     *string `json:"notes,omitempty"`
}

type UpdateCleanerProfileInput struct {
	PhoneNumber       *string  `json:"phoneNumber,omitempty"`
	DateOfBirth       *string  `json:"dateOfBirth,omitempty"`
	StreetAddress     *string  `json:"streetAddress,omitempty"`
	City              *string  `json:"city,omitempty"`
	County            *string  `json:"county,omitempty"`
	PostalCode        *string  `json:"postalCode,omitempty"`
	YearsOfExperience *int     `json:"yearsOfExperience,omitempty"`
	Bio               *string  `json:"bio,omitempty"`
	Specializations   []string `json:"specializations,omitempty"`
	Languages         []string `json:"languages,omitempty"`
	Iban              *string  `json:"iban,omitempty"`
	IsAvailable       *bool    `json:"isAvailable,omitempty"`
}

type UpdateClientProfileInput struct {
	FirstName         *string `json:"firstName,omitempty"`
	LastName          *string `json:"lastName,omitempty"`
	PhoneNumber       *string `json:"phoneNumber,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
}

type UpdateCompanyInput struct {
	Name         *string `json:"name,omitempty"`
	Iban         *string `json:"iban,omitempty"`
	BankName     *string `json:"bankName,omitempty"`
	LegalAddress *string `json:"legalAddress,omitempty"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	ContactPhone *string `json:"contactPhone,omitempty"`
}

type UpdatePlatformSettingsInput struct {
	BasePrice                 *float64 `json:"basePrice,omitempty"`
	WeekendMultiplier         *float64 `json:"weekendMultiplier,omitempty"`
	EveningMultiplier         *float64 `json:"eveningMultiplier,omitempty"`
	PlatformFeePercent        *float64 `json:"platformFeePercent,omitempty"`
	EmailNotificationsEnabled *bool    `json:"emailNotificationsEnabled,omitempty"`
	AutoApprovalEnabled       *bool    `json:"autoApprovalEnabled,omitempty"`
	MaintenanceMode           *bool    `json:"maintenanceMode,omitempty"`
}

type UpdateUserProfileInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	Email     *string   `json:"email,omitempty"`
	Phone     *string   `json:"phone,omitempty"`
	Role      UserRole  `json:"role"`
	FirstName *string   `json:"firstName,omitempty"`
	LastName  *string   `json:"lastName,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Client    *Client   `json:"client,omitempty"`
}

type ANAFStatus string

const (
	ANAFStatusPending    ANAFStatus = "PENDING"
	ANAFStatusProcessing ANAFStatus = "PROCESSING"
	ANAFStatusAccepted   ANAFStatus = "ACCEPTED"
	ANAFStatusRejected   ANAFStatus = "REJECTED"
	ANAFStatusFailed     ANAFStatus = "FAILED"
)

var AllANAFStatus = []ANAFStatus{
	ANAFStatusPending,
	ANAFStatusProcessing,
	ANAFStatusAccepted,
	ANAFStatusRejected,
	ANAFStatusFailed,
}

func (e ANAFStatus) IsValid() bool {
	switch e {
	case ANAFStatusPending, ANAFStatusProcessing, ANAFStatusAccepted, ANAFStatusRejected, ANAFStatusFailed:
		return true
	}
	return false
}

func (e ANAFStatus) String() string {
	return string(e)
}

func (e *ANAFStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ANAFStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ANAFStatus", str)
	}
	return nil
}

func (e ANAFStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ANAFStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ANAFStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ApplicationStatus string

const (
	ApplicationStatusDraft       ApplicationStatus = "DRAFT"
	ApplicationStatusSubmitted   ApplicationStatus = "SUBMITTED"
	ApplicationStatusUnderReview ApplicationStatus = "UNDER_REVIEW"
	ApplicationStatusApproved    ApplicationStatus = "APPROVED"
	ApplicationStatusRejected    ApplicationStatus = "REJECTED"
	ApplicationStatusIncomplete  ApplicationStatus = "INCOMPLETE"
)

var AllApplicationStatus = []ApplicationStatus{
	ApplicationStatusDraft,
	ApplicationStatusSubmitted,
	ApplicationStatusUnderReview,
	ApplicationStatusApproved,
	ApplicationStatusRejected,
	ApplicationStatusIncomplete,
}

func (e ApplicationStatus) IsValid() bool {
	switch e {
	case ApplicationStatusDraft, ApplicationStatusSubmitted, ApplicationStatusUnderReview, ApplicationStatusApproved, ApplicationStatusRejected, ApplicationStatusIncomplete:
		return true
	}
	return false
}

func (e ApplicationStatus) String() string {
	return string(e)
}

func (e *ApplicationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApplicationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApplicationStatus", str)
	}
	return nil
}

func (e ApplicationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApplicationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApplicationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ApprovalStatus string

const (
	ApprovalStatusPending  ApprovalStatus = "PENDING"
	ApprovalStatusApproved ApprovalStatus = "APPROVED"
	ApprovalStatusRejected ApprovalStatus = "REJECTED"
)

var AllApprovalStatus = []ApprovalStatus{
	ApprovalStatusPending,
	ApprovalStatusApproved,
	ApprovalStatusRejected,
}

func (e ApprovalStatus) IsValid() bool {
	switch e {
	case ApprovalStatusPending, ApprovalStatusApproved, ApprovalStatusRejected:
		return true
	}
	return false
}

func (e ApprovalStatus) String() string {
	return string(e)
}

func (e *ApprovalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApprovalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApprovalStatus", str)
	}
	return nil
}

func (e ApprovalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApprovalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApprovalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AvailabilityType string

const (
	AvailabilityTypeRecurring AvailabilityType = "RECURRING"
	AvailabilityTypeOneTime   AvailabilityType = "ONE_TIME"
	AvailabilityTypeBlocked   AvailabilityType = "BLOCKED"
)

var AllAvailabilityType = []AvailabilityType{
	AvailabilityTypeRecurring,
	AvailabilityTypeOneTime,
	AvailabilityTypeBlocked,
}

func (e AvailabilityType) IsValid() bool {
	switch e {
	case AvailabilityTypeRecurring, AvailabilityTypeOneTime, AvailabilityTypeBlocked:
		return true
	}
	return false
}

func (e AvailabilityType) String() string {
	return string(e)
}

func (e *AvailabilityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AvailabilityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AvailabilityType", str)
	}
	return nil
}

func (e AvailabilityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AvailabilityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AvailabilityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingFilter string

const (
	BookingFilterAll      BookingFilter = "ALL"
	BookingFilterUpcoming BookingFilter = "UPCOMING"
	BookingFilterPast     BookingFilter = "PAST"
	BookingFilterActive   BookingFilter = "ACTIVE"
)

var AllBookingFilter = []BookingFilter{
	BookingFilterAll,
	BookingFilterUpcoming,
	BookingFilterPast,
	BookingFilterActive,
}

func (e BookingFilter) IsValid() bool {
	switch e {
	case BookingFilterAll, BookingFilterUpcoming, BookingFilterPast, BookingFilterActive:
		return true
	}
	return false
}

func (e BookingFilter) String() string {
	return string(e)
}

func (e *BookingFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingFilter", str)
	}
	return nil
}

func (e BookingFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingStatus string

const (
	BookingStatusPending       BookingStatus = "PENDING"
	BookingStatusConfirmed     BookingStatus = "CONFIRMED"
	BookingStatusInProgress    BookingStatus = "IN_PROGRESS"
	BookingStatusCompleted     BookingStatus = "COMPLETED"
	BookingStatusCancelled     BookingStatus = "CANCELLED"
	BookingStatusDisputed      BookingStatus = "DISPUTED"
	BookingStatusRefunded      BookingStatus = "REFUNDED"
	BookingStatusNoShowClient  BookingStatus = "NO_SHOW_CLIENT"
	BookingStatusNoShowCleaner BookingStatus = "NO_SHOW_CLEANER"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusPending,
	BookingStatusConfirmed,
	BookingStatusInProgress,
	BookingStatusCompleted,
	BookingStatusCancelled,
	BookingStatusDisputed,
	BookingStatusRefunded,
	BookingStatusNoShowClient,
	BookingStatusNoShowCleaner,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusPending, BookingStatusConfirmed, BookingStatusInProgress, BookingStatusCompleted, BookingStatusCancelled, BookingStatusDisputed, BookingStatusRefunded, BookingStatusNoShowClient, BookingStatusNoShowCleaner:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyApprovalStatus string

const (
	CompanyApprovalStatusPending  CompanyApprovalStatus = "PENDING"
	CompanyApprovalStatusApproved CompanyApprovalStatus = "APPROVED"
	CompanyApprovalStatusRejected CompanyApprovalStatus = "REJECTED"
)

var AllCompanyApprovalStatus = []CompanyApprovalStatus{
	CompanyApprovalStatusPending,
	CompanyApprovalStatusApproved,
	CompanyApprovalStatusRejected,
}

func (e CompanyApprovalStatus) IsValid() bool {
	switch e {
	case CompanyApprovalStatusPending, CompanyApprovalStatusApproved, CompanyApprovalStatusRejected:
		return true
	}
	return false
}

func (e CompanyApprovalStatus) String() string {
	return string(e)
}

func (e *CompanyApprovalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyApprovalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyApprovalStatus", str)
	}
	return nil
}

func (e CompanyApprovalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyApprovalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyApprovalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DisputeResolutionType string

const (
	DisputeResolutionTypePartialRefund DisputeResolutionType = "PARTIAL_REFUND"
	DisputeResolutionTypeFullRefund    DisputeResolutionType = "FULL_REFUND"
	DisputeResolutionTypeReclean       DisputeResolutionType = "RECLEAN"
	DisputeResolutionTypeRejected      DisputeResolutionType = "REJECTED"
)

var AllDisputeResolutionType = []DisputeResolutionType{
	DisputeResolutionTypePartialRefund,
	DisputeResolutionTypeFullRefund,
	DisputeResolutionTypeReclean,
	DisputeResolutionTypeRejected,
}

func (e DisputeResolutionType) IsValid() bool {
	switch e {
	case DisputeResolutionTypePartialRefund, DisputeResolutionTypeFullRefund, DisputeResolutionTypeReclean, DisputeResolutionTypeRejected:
		return true
	}
	return false
}

func (e DisputeResolutionType) String() string {
	return string(e)
}

func (e *DisputeResolutionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DisputeResolutionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DisputeResolutionType", str)
	}
	return nil
}

func (e DisputeResolutionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DisputeResolutionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DisputeResolutionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DisputeStatus string

const (
	DisputeStatusOpen        DisputeStatus = "OPEN"
	DisputeStatusUnderReview DisputeStatus = "UNDER_REVIEW"
	DisputeStatusResolved    DisputeStatus = "RESOLVED"
	DisputeStatusClosed      DisputeStatus = "CLOSED"
)

var AllDisputeStatus = []DisputeStatus{
	DisputeStatusOpen,
	DisputeStatusUnderReview,
	DisputeStatusResolved,
	DisputeStatusClosed,
}

func (e DisputeStatus) IsValid() bool {
	switch e {
	case DisputeStatusOpen, DisputeStatusUnderReview, DisputeStatusResolved, DisputeStatusClosed:
		return true
	}
	return false
}

func (e DisputeStatus) String() string {
	return string(e)
}

func (e *DisputeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DisputeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DisputeStatus", str)
	}
	return nil
}

func (e DisputeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DisputeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DisputeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DisputeType string

const (
	DisputeTypeQualityIssue DisputeType = "QUALITY_ISSUE"
	DisputeTypeDamage       DisputeType = "DAMAGE"
	DisputeTypeNoShow       DisputeType = "NO_SHOW"
	DisputeTypePricing      DisputeType = "PRICING"
	DisputeTypeOther        DisputeType = "OTHER"
)

var AllDisputeType = []DisputeType{
	DisputeTypeQualityIssue,
	DisputeTypeDamage,
	DisputeTypeNoShow,
	DisputeTypePricing,
	DisputeTypeOther,
}

func (e DisputeType) IsValid() bool {
	switch e {
	case DisputeTypeQualityIssue, DisputeTypeDamage, DisputeTypeNoShow, DisputeTypePricing, DisputeTypeOther:
		return true
	}
	return false
}

func (e DisputeType) String() string {
	return string(e)
}

func (e *DisputeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DisputeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DisputeType", str)
	}
	return nil
}

func (e DisputeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DisputeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DisputeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft     InvoiceStatus = "DRAFT"
	InvoiceStatusIssued    InvoiceStatus = "ISSUED"
	InvoiceStatusPaid      InvoiceStatus = "PAID"
	InvoiceStatusCancelled InvoiceStatus = "CANCELLED"
)

var AllInvoiceStatus = []InvoiceStatus{
	InvoiceStatusDraft,
	InvoiceStatusIssued,
	InvoiceStatusPaid,
	InvoiceStatusCancelled,
}

func (e InvoiceStatus) IsValid() bool {
	switch e {
	case InvoiceStatusDraft, InvoiceStatusIssued, InvoiceStatusPaid, InvoiceStatusCancelled:
		return true
	}
	return false
}

func (e InvoiceStatus) String() string {
	return string(e)
}

func (e *InvoiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceStatus", str)
	}
	return nil
}

func (e InvoiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type KPIPeriod string

const (
	KPIPeriodToday KPIPeriod = "TODAY"
	KPIPeriodWeek  KPIPeriod = "WEEK"
	KPIPeriodMonth KPIPeriod = "MONTH"
)

var AllKPIPeriod = []KPIPeriod{
	KPIPeriodToday,
	KPIPeriodWeek,
	KPIPeriodMonth,
}

func (e KPIPeriod) IsValid() bool {
	switch e {
	case KPIPeriodToday, KPIPeriodWeek, KPIPeriodMonth:
		return true
	}
	return false
}

func (e KPIPeriod) String() string {
	return string(e)
}

func (e *KPIPeriod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KPIPeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KPIPeriod", str)
	}
	return nil
}

func (e KPIPeriod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KPIPeriod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KPIPeriod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentProvider string

const (
	PaymentProviderNetopia PaymentProvider = "NETOPIA"
	PaymentProviderManual  PaymentProvider = "MANUAL"
)

var AllPaymentProvider = []PaymentProvider{
	PaymentProviderNetopia,
	PaymentProviderManual,
}

func (e PaymentProvider) IsValid() bool {
	switch e {
	case PaymentProviderNetopia, PaymentProviderManual:
		return true
	}
	return false
}

func (e PaymentProvider) String() string {
	return string(e)
}

func (e *PaymentProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentProvider", str)
	}
	return nil
}

func (e PaymentProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentStatus string

const (
	PaymentStatusPending    PaymentStatus = "PENDING"
	PaymentStatusAuthorized PaymentStatus = "AUTHORIZED"
	PaymentStatusCaptured   PaymentStatus = "CAPTURED"
	PaymentStatusFailed     PaymentStatus = "FAILED"
	PaymentStatusRefunded   PaymentStatus = "REFUNDED"
	PaymentStatusCancelled  PaymentStatus = "CANCELLED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusPending,
	PaymentStatusAuthorized,
	PaymentStatusCaptured,
	PaymentStatusFailed,
	PaymentStatusRefunded,
	PaymentStatusCancelled,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusPending, PaymentStatusAuthorized, PaymentStatusCaptured, PaymentStatusFailed, PaymentStatusRefunded, PaymentStatusCancelled:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentType string

const (
	PaymentTypePreauthorization PaymentType = "PREAUTHORIZATION"
	PaymentTypeCapture          PaymentType = "CAPTURE"
	PaymentTypeRefund           PaymentType = "REFUND"
	PaymentTypeCancellation     PaymentType = "CANCELLATION"
)

var AllPaymentType = []PaymentType{
	PaymentTypePreauthorization,
	PaymentTypeCapture,
	PaymentTypeRefund,
	PaymentTypeCancellation,
}

func (e PaymentType) IsValid() bool {
	switch e {
	case PaymentTypePreauthorization, PaymentTypeCapture, PaymentTypeRefund, PaymentTypeCancellation:
		return true
	}
	return false
}

func (e PaymentType) String() string {
	return string(e)
}

func (e *PaymentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentType", str)
	}
	return nil
}

func (e PaymentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "PENDING"
	PayoutStatusProcessing PayoutStatus = "PROCESSING"
	PayoutStatusSent       PayoutStatus = "SENT"
	PayoutStatusFailed     PayoutStatus = "FAILED"
	PayoutStatusCancelled  PayoutStatus = "CANCELLED"
)

var AllPayoutStatus = []PayoutStatus{
	PayoutStatusPending,
	PayoutStatusProcessing,
	PayoutStatusSent,
	PayoutStatusFailed,
	PayoutStatusCancelled,
}

func (e PayoutStatus) IsValid() bool {
	switch e {
	case PayoutStatusPending, PayoutStatusProcessing, PayoutStatusSent, PayoutStatusFailed, PayoutStatusCancelled:
		return true
	}
	return false
}

func (e PayoutStatus) String() string {
	return string(e)
}

func (e *PayoutStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PayoutStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PayoutStatus", str)
	}
	return nil
}

func (e PayoutStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PayoutStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PayoutStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PhotoType string

const (
	PhotoTypeBefore          PhotoType = "BEFORE"
	PhotoTypeAfter           PhotoType = "AFTER"
	PhotoTypeDisputeEvidence PhotoType = "DISPUTE_EVIDENCE"
)

var AllPhotoType = []PhotoType{
	PhotoTypeBefore,
	PhotoTypeAfter,
	PhotoTypeDisputeEvidence,
}

func (e PhotoType) IsValid() bool {
	switch e {
	case PhotoTypeBefore, PhotoTypeAfter, PhotoTypeDisputeEvidence:
		return true
	}
	return false
}

func (e PhotoType) String() string {
	return string(e)
}

func (e *PhotoType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PhotoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PhotoType", str)
	}
	return nil
}

func (e PhotoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PhotoType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PhotoType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReviewerRole string

const (
	ReviewerRoleClient  ReviewerRole = "CLIENT"
	ReviewerRoleCleaner ReviewerRole = "CLEANER"
)

var AllReviewerRole = []ReviewerRole{
	ReviewerRoleClient,
	ReviewerRoleCleaner,
}

func (e ReviewerRole) IsValid() bool {
	switch e {
	case ReviewerRoleClient, ReviewerRoleCleaner:
		return true
	}
	return false
}

func (e ReviewerRole) String() string {
	return string(e)
}

func (e *ReviewerRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewerRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewerRole", str)
	}
	return nil
}

func (e ReviewerRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewerRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewerRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceType string

const (
	ServiceTypeStandard       ServiceType = "STANDARD"
	ServiceTypeDeepCleaning   ServiceType = "DEEP_CLEANING"
	ServiceTypeOffice         ServiceType = "OFFICE"
	ServiceTypePostRenovation ServiceType = "POST_RENOVATION"
	ServiceTypeMoveInOut      ServiceType = "MOVE_IN_OUT"
)

var AllServiceType = []ServiceType{
	ServiceTypeStandard,
	ServiceTypeDeepCleaning,
	ServiceTypeOffice,
	ServiceTypePostRenovation,
	ServiceTypeMoveInOut,
}

func (e ServiceType) IsValid() bool {
	switch e {
	case ServiceTypeStandard, ServiceTypeDeepCleaning, ServiceTypeOffice, ServiceTypePostRenovation, ServiceTypeMoveInOut:
		return true
	}
	return false
}

func (e ServiceType) String() string {
	return string(e)
}

func (e *ServiceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceType", str)
	}
	return nil
}

func (e ServiceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleClient        UserRole = "CLIENT"
	UserRoleCleaner       UserRole = "CLEANER"
	UserRoleCompanyAdmin  UserRole = "COMPANY_ADMIN"
	UserRolePlatformAdmin UserRole = "PLATFORM_ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleClient,
	UserRoleCleaner,
	UserRoleCompanyAdmin,
	UserRolePlatformAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleClient, UserRoleCleaner, UserRoleCompanyAdmin, UserRolePlatformAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
